import api from './api'

export const campaignService = {
    getAll: (params) => api.get('/campaigns', { params }),
    getOne: (id) => api.get(`/campaigns/${id}`),
    getTiersByCampaign: (campaignId) => api.get('/tiers', { params: { campaign_id: campaignId } }),
    getBackingsByCampaign: (campaignId) => api.get('/backings', { params: { campaign_id: campaignId } }),
    getUsers: () => api.get('/users'),
    create: (data) => api.post('/campaigns', data),
    createTier: (data) => api.post('/tiers', data),
    createBacking: (data) => api.post('/backings', data),
    updateTierQuota: (tierId, data) => api.patch(`/tiers/${tierId}`, data),
    getBackingsByUser: (userId) => api.get('/backings', { params: { user_id: userId } }),
    getCampaignsByCreator: (creatorId) => api.get('/campaigns', { params: { creator_id: creatorId } }),
    updateCampaignAmount: (campaignId, data) => api.patch(`/campaigns/${campaignId}`, data),
    getUserById: (userId) => api.get(`/users/${userId}`),
    updateStatus: (campaignId, status) => api.patch(`/campaigns/${campaignId}`, { status }),
    getCampaignsByStatus: (status) => api.get('/campaigns', { params: { status } }),
    getAllUsers: () => api.get('/users'),
    updateUserStatus: (userId, isSuspended) => api.patch(`/users/${userId}`, { is_suspended: isSuspended }),
    getNotificationsByUser: (userId) => api.get('/notifications', { params: { user_id: userId } }),
    markNotificationAsRead: (notifId) => api.patch(`/notifications/${notifId}`, { is_read: true }),
    getUpdatesByCampaign: (campaignId) => api.get('/campaign_updates', { params: { campaign_id: campaignId } }),
    createUpdate: (data) => api.post('/campaign_updates', data),
}